[
    {
        "id": "$id_model_selector",
        "id_server": "$id_modbus_client",
        "type": "supmodel",
        "z": "",
        "selectedModel": "$model_topic",
        "modelSchema": "$schema_json_string",
        "modelMapping": "$mapping_string",
        "x": 610,
        "y": 80,
        "wires": [
            [
                "$id_mqtt"
            ],
            [

            ]
        ]
    },
    {
        "id": "$id_mqtt",
        "type": "mqtt out",
        "z": "",
        "name": "",
        "topic": "",
        "qos": "",
        "retain": "",
        "respTopic": "",
        "contentType": "",
        "userProps": "",
        "correl": "",
        "expiry": "",
        "broker": "85bb67b2dbefe3ba",
        "x": 900,
        "y": 80,
        "wires": []
    },
    {
        "id": "$id_modbus_read",
        "type": "modbus-read",
        "z": "",
        "name": "",
        "topic": "",
        "showStatusActivities": false,
        "logIOActivities": false,
        "showErrors": true,
        "showWarnings": true,
        "unitid": "$modbus_unit_id",
        "dataType": "$modbus_func_code",
        "adr": "$modbus_adr",
        "quantity": "$modbus_quantity",
        "rate": "$modbus_rate",
        "rateUnit": "$Modbus_rate_unit",
        "delayOnStart": false,
        "startDelayTime": "",
        "server": "$id_modbus_client",
        "useIOFile": false,
        "ioFile": "",
        "useIOForPayload": false,
        "emptyMsgOnFail": false,
        "x": 350,
        "y": 80,
        "wires": [
            [
                "$id_model_selector"
            ],
            []
        ]
    },
    {
        "id": "85bb67b2dbefe3ba",
        "type": "mqtt-broker",
        "name": "",
        "broker": "emqx",
        "port": "1883",
        "clientid": "",
        "autoConnect": true,
        "usetls": false,
        "protocolVersion": "4",
        "keepalive": "60",
        "cleansession": true,
        "autoUnsubscribe": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthRetain": "false",
        "birthPayload": "",
        "birthMsg": {},
        "closeTopic": "",
        "closeQos": "0",
        "closeRetain": "false",
        "closePayload": "",
        "closeMsg": {},
        "willTopic": "",
        "willQos": "0",
        "willRetain": "false",
        "willPayload": "",
        "willMsg": {},
        "userProps": "",
        "sessionExpiry": ""
    },
    {
        "id": "$id_modbus_client",
        "type": "modbus-client",
        "z": "",
        "name": "$modbus_client_name",
        "clienttype": "tcp",
        "bufferCommands": true,
        "stateLogEnabled": false,
        "queueLogEnabled": false,
        "failureLogEnabled": true,
        "tcpHost": "$modbus_host",
        "tcpPort": "$modbus_port",
        "tcpType": "DEFAULT",
        "serialPort": "/dev/ttyUSB",
        "serialType": "RTU-BUFFERD",
        "serialBaudrate": "9600",
        "serialDatabits": "8",
        "serialStopbits": "1",
        "serialParity": "none",
        "serialConnectionDelay": "100",
        "serialAsciiResponseStartDelimiter": "0x3A",
        "unit_id": "$modbus_unit_id",
        "commandDelay": "1",
        "clientTimeout": "1000",
        "reconnectOnTimeout": true,
        "reconnectTimeout": "2000",
        "parallelUnitIdsAllowed": true,
        "showErrors": false,
        "showWarnings": true,
        "showLogs": true
    }
]