[
    {
        "id": "$mqtt_in_id",
        "id_server": "$mqtt_broker_input_id",
        "type": "mqtt in",
        "z": "",
        "name": "$mqtt_in_name",
        "topic": "$mqtt_topic_input",
        "qos": "0",
        "datatype": "auto-detect",
        "broker": "$mqtt_broker_input_id",
        "nl": false,
        "rap": true,
        "rh": 0,
        "inputs": 0,
        "x": 150,
        "y": 180,
        "wires": [
            [
                "$id_model_selector"
            ]
        ]
    },
    {
            "id": "$id_model_selector",
            "type": "supmodel",
            "z": "",
            "selectedModel": "$model_topic",
            "modelSchema": "$schema_json_string",
            "modelMapping": "",
            "x": 550,
            "y": 180,
            "wires": [
                [
                    "$mqtt_out_id"
                ],
                [

                ]
            ]
        },
	{
        "id": "$mqtt_out_id",
        "type": "mqtt out",
        "z": "",
        "name": "",
        "topic": "",
        "qos": "0",
        "retain": "false",
        "respTopic": "",
        "contentType": "",
        "userProps": "",
        "correl": "",
        "expiry": "",
        "broker": "85bb67b2dbefe3ba",
        "x": 1090,
        "y": 180,
        "wires": []
    },
    {
        "id": "85bb67b2dbefe3ba",
        "type": "mqtt-broker",
        "name": "",
        "broker": "emqx",
        "port": "1883",
        "clientid": "",
        "autoConnect": true,
        "usetls": false,
        "protocolVersion": "4",
        "keepalive": "60",
        "cleansession": true,
        "autoUnsubscribe": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthRetain": "false",
        "birthPayload": "",
        "birthMsg": {},
        "closeTopic": "",
        "closeQos": "0",
        "closeRetain": "false",
        "closePayload": "",
        "closeMsg": {},
        "willTopic": "",
        "willQos": "0",
        "willRetain": "false",
        "willPayload": "",
        "willMsg": {},
        "userProps": "",
        "sessionExpiry": ""
    },
    {
        "id": "$mqtt_broker_input_id",
        "type": "mqtt-broker",
		"z": "",
        "name": "$mqtt_broker_input_name",
        "broker": "$mqtt_broker_input_host",
        "port": $mqtt_broker_input_port,
        "clientid": "",
        "autoConnect": true,
        "credentials":{user: "$mqtt_broker_input_credential_user", password: "$mqtt_broker_input_credential_password"},
        "usetls": false,
        "protocolVersion": 4,
        "keepalive": 60,
        "cleansession": true,
        "autoUnsubscribe": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthRetain": "false",
        "birthPayload": "",
        "birthMsg": {},
        "closeTopic": "",
        "closeQos": "0",
        "closeRetain": "false",
        "closePayload": "",
        "closeMsg": {},
        "willTopic": "",
        "willQos": "0",
        "willRetain": "false",
        "willPayload": "",
        "willMsg": {},
        "userProps": "",
        "sessionExpiry": ""
    }
]